### ISSUE TITLE
Footer bug

### ISSUE THREAD

**Issue by DibashShrestha** [SakshyamShrestha/Online-Library#12]
@SushantPokharel316  The color contrast of the footer is mismatched

**Comment by DibashShrestha** [comment]
While browsing our website I found that the colour of footer is mismatched which might be a bit difficult for user so please change the colour of the links in the footer.

**Comment by SushantPokharel316** [comment]
sure, I will look into it

**Comment by SushantPokharel316** [comment]
It is now solved in the latest commit
