### ISSUE TITLE
Registration form bug

### ISSUE THREAD

**Issue by DibashShrestha17** [SakshyamShrestha/Online-Library#6]
Email field in the registration form does not inherit the CSS.

**Comment by SakshyamShrestha** [comment]
I am looking into the issue looks like the form.email doesn't work.

**Comment by SushantPokharel316** [comment]
Looks like separate library integrations are required for email field to inherit default CSS property.

**Comment by SakshyamShrestha** [comment]
I have resolved the issue, please review the update
